### ISSUE TITLE
Add event banner to OSM website

### ISSUE THREAD

**Issue by maning** [sotm-asia/sotm-asia-2017-website#8]

**Comment by kshitizkhanal7** [comment]
@maning Can you be more descriptive? Or post examples.

**Comment by seav** [comment]
Just follow this [previous PR](https://github.com/openstreetmap/openstreetmap-website/pull/1258) for SotM Asia 2016. Somebody needs to create a 350-pixel wide banner, then update the banners.yml file.

**Comment by kshitizkhanal7** [comment]
banner already up!
